fix favicon
Unirep/trusted-setup pull request #96
Opened 2023-09-20 19:38 UTC by kittybest

close #93 .

2023-09-22 02:56 UTC, vivianjeng requested changes
You should change the favicon path in `webpack.config.js`
(I am not sure the `webpack.worker.js` is used for)
But favicon should be previewed in cloudflare environment
like this
https://34c87077.trusted-setup-favicon.pages.dev/

2023-09-22 02:57 UTC, vivianjeng commented
And I prefer favicon to be like this
<img width="128" alt="截圖 2023-09-22 上午10 56 42" src="https://github.com/Unirep/trusted-setup/assets/17507085/051b1072-30f8-4b41-abd5-3d69eced5664">
@ChialiT ?

2023-09-22 13:32 UTC, ChialiT commented
> And I prefer favicon to be like this <img alt="截圖 2023-09-22 上午10 56 42" width="128" src="https://user-images.githubusercontent.com/17507085/269816334-051b1072-30f8-4b41-abd5-3d69eced5664.png"> @ChialiT ?

This one is better, stand out more.

2023-09-27 01:57 UTC, kittybest commented
> You should change the favicon path in `webpack.config.js` (I am not sure the `webpack.worker.js` is used for) But favicon should be previewed in cloudflare environment like this https://34c87077.trusted-setup-favicon.pages.dev/

That's my fault, I just saw I modified the wrong file 😅

2023-09-27 02:05 UTC, kittybest commented
<img width="138" alt="image" src="https://github.com/Unirep/trusted-setup/assets/9023842/ca0ba9f3-819f-4d58-be00-108f25e483f9">
Or are you saying the one without background color? only with the unirep logo in blue?

2023-09-27 11:55 UTC, vivianjeng commented
I think with black background

2023-09-28 20:38 UTC, kittybest commented
then @ChialiT could you give me a `.svg` version of this logo with black background? I only have the screenshot, and can only find the one without any background in figma.

2023-09-29 13:34 UTC, ChialiT commented
> then @ChialiT could you give me a `.svg` version of this logo with black background? I only have the screenshot, and can only find the one without any background in figma.

tag you in the figma

2023-10-03 05:28 UTC, kittybest commented
<img width="266" alt="image" src="https://github.com/Unirep/trusted-setup/assets/9023842/81a342da-4832-4896-95c6-cf317757c2ec">
It looks good in search bar in safari browser, but

<img width="170" alt="image" src="https://github.com/Unirep/trusted-setup/assets/9023842/b33003c0-2df9-427b-9974-2a53f4961246">
is added white border while on tab in safari browser.

2023-10-03 05:53 UTC, vivianjeng approved these changes

2023-10-03 05:53 UTC, vivianjeng commented on packages/frontend/webpack.worker.js
> +const HtmlWebpackPlugin = require('html-webpack-plugin')
I think it is not used in this file?

2023-10-03 06:35 UTC, merged