Share to Social Media
Unirep/trusted-setup pull request #99
Opened 2023-09-27 01:30 UTC by kittybest

- change `oauth()` function in `ceremony context` (Q: should we put the posting stuff in this context? or new a context related to `oauth` stuff)
- add posting function in backend in `github` router
- adjust the oauth-token scope for github
-

2023-10-03 13:58 UTC, kittybest commented
I already deployed the backend to `https://http.ceremony.unirep.io` and I think it works well now.
@vivianjeng

2023-10-03 14:18 UTC, ChialiT commented
<img width="591" alt="image" src="https://github.com/Unirep/trusted-setup/assets/16527634/c2da9373-ae22-494a-b232-1fbae7debe61">


this does posted on twitter, but the behavior is weird tho.
first it asked me to authorized, and the project is called UniRep Social (we should be called UniRep)
then it didn't let me preview the tweet, it just post it without my consensus.

2023-10-03 14:26 UTC, kittybest commented
@ChialiT 
- Should be [Anon] --> this part is an issue I opened: #103 , is a problem not only related to this `share-sns` branch, so I don't want to fix it this  PR.
- Unirep Social is because I use my old twitter oauth token... I cannot apply for a second token since I don't pay for it, but of course I can change the name to **Unirep Trusted Setup** since unirep social is not working now.
- without preview --> I cannot imagine how will it work with preview? The user will be redirected to twitter and they can go to anywhere else instead of posting and might lost their way back to the ceremony? Do you have example website of how this work?

2023-10-03 14:30 UTC, ChialiT commented
> @ChialiT
> 
> * Should be [Anon] --> this part is an issue I opened: [[Frontend] Username #103](https://github.com/Unirep/trusted-setup/issues/103) , is a problem not only related to this `share-sns` branch, so I don't want to fix it this  PR.
> * Unirep Social is because I use my old twitter oauth token... I cannot apply for a second token since I don't pay for it, but of course I can change the name to **Unirep Trusted Setup** since unirep social is not working now.
> * without preview --> I cannot imagine how will it work with preview? The user will be redirected to twitter and they can go to anywhere else instead of posting and might lost their way back to the ceremony? Do you have example website of how this work?

<img width="537" alt="image" src="https://github.com/Unirep/trusted-setup/assets/16527634/34b20de2-45e3-42c3-9dc0-8fd977a43007">
the preview just an typical OG image, if you have set up some kinda SEO on the site, it should be render.

like the kzg ceremony
<img width="536" alt="image" src="https://github.com/Unirep/trusted-setup/assets/16527634/1777b3f0-e169-4b19-ad4d-ed5b998c3237">

2023-10-03 14:45 UTC, kittybest commented
@ChialiT 
Oh I don't know what is an OG picture and now I know. I will add it. (I thought it will appear directly after we setup our frontend settings... but it seems like we could do something to make it more customizable.)
Btw, I think we could do like **we post for the user on gist/twitter ➡️ back to ceremony webpage but display a popup box providing a button to go to their post**, now the users need to check by themselves and it's not that convenient.
Also I just think of that the displayed URL in the post is wrong (that's the url of the backend not frontend), I will modify it now.

2023-10-03 20:06 UTC, CJ-Rose commented
my twitter post looks like this
<img width="590" alt="Screenshot 2023-10-03 at 12 49 35 PM" src="https://github.com/Unirep/trusted-setup/assets/79813968/f1284285-7a4e-409f-bfd6-0b28a60088be">

if i saw someone post this i would not have any idea what it was about. i think we should change the copy here, it would be more clear if we simply say 'I just contributed to UniRep trusted setup ceremony.' and then 'Generate your (own) verse and help secure the UniRep protocol here:'

and the second line of text should not be repeated both in the body of the post and in the link.

2023-10-03 20:08 UTC, ChialiT commented
> my twitter post looks like this <img alt="Screenshot 2023-10-03 at 12 49 35 PM" width="590" src="https://user-images.githubusercontent.com/79813968/272382253-f1284285-7a4e-409f-bfd6-0b28a60088be.png">
> 
> if i saw someone post this i would not have any idea what it was about. i think we should change the copy here, it would be more clear if we simply say 'I just contributed to UniRep trusted setup ceremony.' and then 'Generate your (own) verse and help secure the UniRep protocol here:'
> 
> and the second line of text should not be repeated both in the body of the post and in the link.

yes, more clear copy. thank you!

2023-10-04 01:22 UTC, vivianjeng commented
<img width="599" alt="截圖 2023-10-04 上午9 16 21" src="https://github.com/Unirep/trusted-setup/assets/17507085/c0fdcea8-7b72-4939-b43d-fa3d332dc035">

when I click **Github** it redirects to `localhost:8000`

2023-10-04 01:51 UTC, ChialiT commented
✨ UniRep Ceremony ✨
I just contributed to UniRep trusted setup ceremony.
Generate your own verse and help secure the UniRep protocol here: https://ceremony.unirep.io

2023-10-04 04:04 UTC, vivianjeng commented
I think it can have a logo,  description and url to unirep page (or PSE page) in the Twitter Oauth token

![image](https://github.com/Unirep/trusted-setup/assets/17507085/7c18b8d3-414a-421f-a07a-30f8f54cbaf2)

2023-10-04 06:44 UTC, kittybest commented
@ChialiT what kind of logo do you think we should have for our app? I could upload to twitter/discord/github oauth app setting.

2023-10-04 06:47 UTC, kittybest commented
> Generate your own verse and help secure the UniRep protocol.

fixed.

2023-10-04 14:15 UTC, ChialiT commented
> @ChialiT what kind of logo do you think we should have for our app? I could upload to twitter/discord/github oauth app setting. Also need the website description for `og:description` and oath app description.

description: Generate your own verse and help secure the UniRep protocol.

and lets use the same favicon as the app, u should be able to generate the png from figma.

2023-10-05 08:40 UTC, kittybest commented
> > @ChialiT what kind of logo do you think we should have for our app? I could upload to twitter/discord/github oauth app setting. Also need the website description for `og:description` and oath app description.
> 
> description: Generate your own verse and help secure the UniRep protocol.
> 
> and lets use the same favicon as the app, u should be able to generate the png from figma.

Logo and description updated.

2023-10-05 16:27 UTC, CJ-Rose commented
<img width="604" alt="Screenshot 2023-10-05 at 9 19 03 AM" src="https://github.com/Unirep/trusted-setup/assets/79813968/3292e45f-82a9-400c-b99d-59115d19a3aa">

still no image on my post, does it appear for others?

2023-10-08 05:23 UTC, CJ-Rose requested changes

2023-10-08 05:23 UTC, CJ-Rose commented on packages/frontend/src/pages/Contribute.jsx
> +        content={`Post on ${postMessage.platform} successfully.`}
change to:

title="Post Successful!"
content={'Your contribution was posted on ${postMessage.platform}. '}

2023-10-08 05:23 UTC, CJ-Rose commented on packages/frontend/src/pages/Contribute.jsx
> +    )
remove the last line here:
'Generate your own verse and help secure the UniRep protocol'

--and move that text to replace what is currently attached to the link in `index.html`

2023-10-08 05:23 UTC, CJ-Rose commented on packages/frontend/public/index.html
> +      content="Generate your verse to the UniRep Ceremony to knitting together the constellation that unveil our journey."
replace `content` with:

'Generate your own verse and help secure the UniRep protocol.'

2023-10-08 12:00 UTC, vivianjeng reviewed
The webpack will not include the `og.png` in the output folder

it should work like this
https://1bbd14f7.trusted-setup-og.pages.dev/

and you should be able to preview it in this link
https://www.opengraph.xyz/url/https%3A%2F%2F1bbd14f7.trusted-setup-og.pages.dev%2F

2023-10-08 16:03 UTC, merged